name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"

      - name: "Validate Composer"
        run: "composer validate --check-lock --strict"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Test"
        run: "composer test"